#!/bin/bash
yum update -y
yum install -y httpd.x86_64
systemctl start httpd.service
systemctl enable httpd.service
amazon-linux-extras enable php7.4
yum clean metadata
yum install -y php-cli php-pdo php-fpm php-json php-mysqlnd 
systemctl restart httpd.service
aws s3 cp s3://<bucketName>/index.php /var/www/html/index.php
amazon-linux-extras install -y epel
yum install -y stress
